### PR TITLE
Correct someone's drunk keyboard output

### PR DESCRIPTION
**Pull request by pjar**
Correcting a typo in docs

### CODE REVIEW

**Comment by jpalermo** [comment]
Although I don't normally use the test unit matchers, I think the existing example should work.

The README has two examples for `assert_has_search_params`, one that uses the argument matcher syntax, and the one you are modifying which is the block matcher syntax.

The block syntax is normally only needed when you have multiple search statements that you are matching against, but we want to have at least one example of it in the README.

**Comment by pjar** [comment]
The reason for the whole fix was that there was bad syntax. @jpalermo I've brought back block example with how I suppose it should look like originally.

**Comment by jpalermo** [comment]
The syntax should not be bad. Do you get a Ruby error when using the syntax that is currently there?

**Comment by jpalermo** [comment]
Closing due to inactivity.

**Pull request closed without merging**
